version: '3.8'
services:
  payment_service:
    container_name: payment_service
    build:
      context: .
      dockerfile: ./src/main/resources/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - STRIPE_API_KEY=sk_test_51PbgjhF4y4FVctE4n8bMV0axDbTDw2M0Kc96ameus8Zs7Nzb42SxQQaJnfnGISBdWV2F3ezDU7DwxiydRxpM8G6W00dAGB4vwg
      - FRONTEND_URL=http://localhost:3000
    networks:
      - mynetwork



  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_USER=username
    ports:
      - "5675:5672"  # Changed host port to 5675
      - "15674:15672"  # Changed management port to 15674

    restart: always
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge